// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: fxwatcher.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FxWatcherClient is the client API for FxWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FxWatcherClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type fxWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewFxWatcherClient(cc grpc.ClientConnInterface) FxWatcherClient {
	return &fxWatcherClient{cc}
}

func (c *fxWatcherClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/pb.FxWatcher/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxWatcherServer is the server API for FxWatcher service.
// All implementations must embed UnimplementedFxWatcherServer
// for forward compatibility
type FxWatcherServer interface {
	Call(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedFxWatcherServer()
}

// UnimplementedFxWatcherServer must be embedded to have forward compatible implementations.
type UnimplementedFxWatcherServer struct {
}

func (UnimplementedFxWatcherServer) Call(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedFxWatcherServer) mustEmbedUnimplementedFxWatcherServer() {}

// UnsafeFxWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FxWatcherServer will
// result in compilation errors.
type UnsafeFxWatcherServer interface {
	mustEmbedUnimplementedFxWatcherServer()
}

func RegisterFxWatcherServer(s grpc.ServiceRegistrar, srv FxWatcherServer) {
	s.RegisterService(&FxWatcher_ServiceDesc, srv)
}

func _FxWatcher_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxWatcherServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxWatcher/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxWatcherServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FxWatcher_ServiceDesc is the grpc.ServiceDesc for FxWatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FxWatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FxWatcher",
	HandlerType: (*FxWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _FxWatcher_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fxwatcher.proto",
}
