{
 "title": "GPU Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "origin_prometheus",
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}