{
 "title": "Kubernetes Pod Resources Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Prometheus Status",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "NameSpace",
    "label": "NameSpace",
    "query": {
     "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Resource Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod CPU (Usage)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$NameSpace\",pod=~\"$Pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory (Usage)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "RSS：{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "limits：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Disk I/O (Read Bytes)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=~\"$NameSpace\",pod=~\"$Pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Disk I/O (Write Bytes)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=~\"$NameSpace\",pod=~\"$Pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network (Usage)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Statistics",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"} == 1"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (pod) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (pod)) * 100"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (pod)",
     "legendFormat": "CPU核数使用"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) by (pod)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod) * 100",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod) * 100",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (pod)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"} - 0"
    },
    {
     "expr": "cass_jvm_heap{service=~\"$Pod\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "cass_jvm_heap_max{service=~\"$Pod\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "cass_jvm_noheap{service=~\"$Pod\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "cass_jvm_noheap_max{service=~\"$Pod\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
    }
   ]
  }
 ]
}