apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-metrics-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
    namespace: monitoring
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce # required
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sujin-worker-1
