apiVersion: v1
kind: Pod
metadata:
  name: gedge-service-application
  namespace: gedge-platform
spec:
  containers:
    - name: app
      image: ubuntu:latest
      command: ["echo"]
      args: ["streamlit run app.py"]
    - name: nginx
      image: nginx:latest
