apiVersion: v1
kind: Service
metadata:
  name: gedge-handler-application
  namespace: gedge-platform
  labels:
    run: gedge-handler-application
spec:
  type: NodePort
  ports:
  - port: 9010
    targetPort: 9010
    name: http
    nodePort: 32226
    protocol: TCP
  # - port: 443
  #   name: https
  #   protocol: TCP  
  selector:
    run: gedge-handler-application
