apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache-pv-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 1
    [[runners]]
      name = "kubernetes-runner"
      url = "https://gitlab.com/imxsuu/imxsuu.git"
      token = "glpat-NYsC7S9ysm8pEjHWWSeR"
      executor = "kubernetes"
      disable_cache = false
      cache_dir = "/cache"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "ubuntu:20.04"
        privileged = true
        [[runners.kubernetes.volumes.pvc]]
          name = "gitlab-runner-cache-pv-claim"
          mount_path = "/cache"
