apiVersion: v1
kind: Service
metadata:
  name: fxgateway
  namespace: openfx
  labels:
    app: fxgateway
spec:
  type: NodePort
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 10000
      nodePort: 31113
  selector:
    app: fxgateway
