apiVersion: v1
kind: Service
metadata:
  name: gedge-app
  namespace: gedge-platform
  labels:
    run: gedge-app
spec:
  type: NodePort
  ports:
  - port: 9010
    targetPort: 9010
    name: http
    nodePort: 32225
    protocol: TCP
  # - port: 443
  #   name: https
  #   protocol: TCP  
  selector:
    run: gedge-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gedge-app
  namespace: gedge-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gedge-app
  template:
    metadata:
      labels:
        run: gedge-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: gedge-app
          image: 10.0.0.183:5000/gedge-app
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
              protocol: TCP
